version: '3'

services:
  # node:
  #   image: node:12
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./:/src/app
  #   command: npm i
  #   command: ./node_modules/.bin/ts-node-dev index.ts
  #   working_dir: /src/app

  nginx:
    image: nginx:alpine
    ports:
      - '443:443'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/secure:/etc/ssl
    working_dir: /src/app
